name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/preview
      # - main
      # - develop
      # - feature/**

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24        # latest LTS (2025-05)

      - name: Enable pnpm and automatic caching
        uses: pnpm/action-setup@v3
        with:
          version: 10.10.0            # matches packageManager field in package.json
          cache: true                 # caches ~/.pnpm-store
          run_install: false          # run manually

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy
        uses: actions/deploy-pages@v4

